services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=simuladorcredito
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simulador-net
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - simulador-net
  emulator:
    container_name: eventhubs-emulator
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    environment:
      - BLOB_SERVER=azurite
      - METADATA_SERVER=azurite
      - ACCEPT_EULA=Y
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    depends_on:
      - azurite
    networks:
      eh-emulator:
        aliases:
          - "eventhubs-emulator"
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    pull_policy: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      eh-emulator:
        aliases:
          - "azurite"
  simulador-credito:
    image: izuca/simuladorcredito:latest
    container_name: simulador-credito
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simuladorcredito
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - emulator
    networks:
      - simulador-net
      - eh-emulator
networks:
  simulador-net:
    driver: bridge
  eh-emulator: