version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - simulador-net
  emulator:
    container_name: eventhubs-emulator
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    environment:
      - BLOB_SERVER=azurite
      - METADATA_SERVER=azurite
      - ACCEPT_EULA=Y
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    depends_on:
      - azurite
    networks:
      eh-emulator:
        aliases:
          - "eventhubs-emulator"
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    pull_policy: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      eh-emulator:
        aliases:
          - "azurite"
networks:
  simulador-net:
    driver: bridge
  eh-emulator: