CREATE DATABASE SimuladorCredito;
GO

USE SimuladorCredito;
GO
CREATE TABLE dbo.PRODUTO (
	CO_PRODUTO INT NOT NULL PRIMARY KEY,
	NO_PRODUTO VARCHAR(200) NOT NULL,
	PC_TAXA_JUROS NUMERIC(10,9) NOT NULL,
	NU_MINIMO_MESES SMALLINT NOT NULL,
	NU_MAXIMO_MESES SMALLINT NULL,
	VR_MINIMO NUMERIC(18,2) NOT NULL,
	VR_MAXIMO NUMERIC(18,2) NULL
);

INSERT INTO dbo.PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS,NU_MINIMO_MESES,NU_MAXIMO_MESES,VR_MINIMO,VR_MAXIMO)
VALUES(1,'Produto 1', 0.017900000, 0, 24, 200.00, 10000.00);

INSERT INTO dbo.PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS,NU_MINIMO_MESES,NU_MAXIMO_MESES,VR_MINIMO,VR_MAXIMO)
VALUES(2,'Produto 2', 0.017500000, 25, 48, 10001.00, 100000.00);

INSERT INTO dbo.PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS,NU_MINIMO_MESES,NU_MAXIMO_MESES,VR_MINIMO,VR_MAXIMO)
VALUES(3,'Produto 3', 0.018200000, 49, 96, 100000.01, 1000000.00);

INSERT INTO dbo.PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS,NU_MINIMO_MESES,NU_MAXIMO_MESES,VR_MINIMO,VR_MAXIMO)
VALUES(4,'Produto 4', 0.015100000, 96, NULL, 1000000.01, NULL);

CREATE TABLE dbo.SIMULACAO (
    ID_SIMULACAO INT IDENTITY(1,1) PRIMARY KEY,
    VR_DESEJADO NUMERIC(18,2) NOT NULL,
    PRAZO INT NOT NULL,
    DATA_HORA DATETIME DEFAULT GETDATE(),
    CO_PRODUTO INT NOT NULL,
    CONSTRAINT FK_SIMULACAO_PRODUTO FOREIGN KEY (CO_PRODUTO) REFERENCES dbo.PRODUTO(CO_PRODUTO)
);

CREATE TABLE dbo.PARCELA (
    ID_PARCELA INT IDENTITY(1,1) PRIMARY KEY,
    TIPO VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    VR_AMORTIZACAO NUMERIC(18,2) NOT NULL,
    VR_JUROS NUMERIC(10,9) NOT NULL,
    VR_PRESTACAO NUMERIC(18,2) NOT NULL,
    ID_SIMULACAO INT NOT NULL,
    CONSTRAINT FK_PARCELA_SIMULACAO FOREIGN KEY (ID_SIMULACAO) REFERENCES dbo.SIMULACAO(ID_SIMULACAO)
);
